[package]
name = "icm42688p"
version = "0.1.0"
edition = "2021"

license = "MIT OR Apache-2.0"
categories = ["embedded", "hardware-support", "no-std"]

[dependencies]
bitflags = "2.9"
embedded-hal = "1.0"
